language: python

python:
  - "3.9"

services: mysql

env:
  global:
    - DJANGO_SETTINGS_MODULE="Da_Roca.settings"
    - PYTHONPATH="/home/travis/build/irisviana/Da_Roca"
    - PIP_USE_MIRRORS=true
    - BUILD_ON_TRAVIS=true
    - FIREFOXDRIVER_PATH="Da_Roca/geckodriver-v0.29.1-linux64/geckodriver"
  matrix:
    - DJANGO=1.7 DB=sqlite3

#commands to install dependencies
install:
  - pip install -q Django==$DJANGO
  - pip install -q -r requirements.txt

before_script:
  - python manage.py makemigrations
  - python manage.py migrate


#command to run the test suite
script:
  - python manage.py test