language: python

python:
  - "3.9"

addons:
  firefox: 
    - "89.0.2"

env:
  global:
    - DJANGO_SETTINGS_MODULE="Da_Roca.settings"
    - PYTHONPATH="/home/travis/build/irisviana/Da_Roca"
    - PIP_USE_MIRRORS=true
    - BUILD_ON_TRAVIS=true
    - TEST_ON_CHROME=off
    - TEST_ON_FIREFOX=on
    - FIREFOXDRIVER_PATH="/usr/local/bin/geckodriver"
  matrix:
    - DJANGO=1.7 DB=sqlite3

#commands to install dependencies
install:
  - pip install -q Django==$DJANGO
  - pip install -q -r requirements.txt

before_script:
  - wget "https://github.com/mozilla/geckodriver/releases/download/v0.29.1/geckodriver-v0.29.1-linux32.tar.gz"
  - tar xfz geckodriver-v0.24.0-linux64.tar.gz
  - sudo mv geckodriver /usr/local/bin
  - python manage.py makemigrations
  - python manage.py migrate


#command to run the test suite
script:
  - python manage.py test
